### ISSUE TITLE
Unable to resolve mandel-contracts path 

### ISSUE THREAD

**Issue by scottoau** [eosnetworkfoundation/DUNE#17]
Hi Guys, 

Testing DUNE on Intel Mac 2019 and getting the following errors during chain setup. 

`dune --bootstrap-system
Preactivate Features: {"code":500,"message":"Internal Service Error","error":{"code":3250000,"name":"protocol_feature_exception","what":"Protocol feature exception","details":[{"message":"protocol feature with digest '0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd' has already been activated","file":"controller.cpp","line_number":1901,"method":"check_protocol_features"}]}}
error 2022-07-20T08:13:27.834 cleos     main.cpp:4121                 operator()           ] Failed with error: 0 exception: unspecified
Unable to resolve path '/home/www-data/mandel-contracts/build/contracts/eosio.boot'
    {"path":"/home/www-data/mandel-contracts/build/contracts/eosio.boot","exception":"Dynamic exception type: boost::filesystem::filesystem_error\nstd::exception::what: boost::filesystem::canonical: No such file or directory: \"/home/www-data/mandel-contracts/build/contracts/eosio.boot\"\n"}
    cleos  filesystem.cpp:361 canonical`

---- 
Checking the container, there is no 'mandel-contracts' directory:

`www-data@a16fb3543669:~$ ls -lah
total 32K
drwxr-xr-x 1 www-data www-data 4.0K Jul 18 04:06 .
drwxr-xr-x 1 root     root     4.0K Jul 18 04:02 ..
-rw-r--r-- 1 www-data www-data   49 Jul 19 13:11 .dune.ctx
-rw-r--r-- 1 www-data www-data  621 Jul 18 04:02 config.ini
drwxr-xr-x 2 www-data www-data 4.0K Jul 19 13:11 eosio-wallet
drwxr-xr-x 1 www-data www-data 4.0K Jul 18 04:04 nodes
-rw-r--r-- 1 www-data www-data    0 Jul 19 13:11 test1.out`

I'm also receiving an error when trying to use the wallet. 

`Error 3120006: No available wallet
Ensure that you have created a wallet and have it open
Error Details:
You don't have any wallet!`

This is coming together, and I can see where it is going! Great stuff.

**Comment by ericpassmore** [comment]
wallet create error covered in issue #15

**Comment by larryk85** [comment]
This should be resolved as of v1.0.0-rc1

**Comment by scottoau** [comment]
Tested version v1.0.0-rc1 on Intel Mac 2019 error still exists:

`❯ ./dune --set-bios-contract 'eosio'
error 2022-07-26T04:19:12.649 cleos     main.cpp:4121                 operator()           ] Failed with error: 0 exception: unspecified
Unable to resolve path '/home/www-data/mandel-contracts/build/contracts/eosio.bios'
    {"path":"/home/www-data/mandel-contracts/build/contracts/eosio.bios","exception":"Dynamic exception type: boost::filesystem::filesystem_error\nstd::exception::what: boost::filesystem::canonical: No such file or directory: \"/home/www-data/mandel-contracts/build/contracts/eosio.bios\"\n"}
    cleos  filesystem.cpp:361 canonical`

Exec to the container, contracts were found '/app/mandel-contracts', nothing in '/home/www-data'. 

Thanks.
